services:
  backend:
    build: ./backend
    container_name: audit_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: audit_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:5000   
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always